In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Salaries.csv")
df.head(2)

C:\Users\2419a\AppData\Local\Temp\ipykernel_11332\2585039687.py:1: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Salaries.csv")


Id    EmployeeName                                        JobTitle  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2    GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   

     BasePay OvertimePay   OtherPay Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.0  400184.25      NaN  567595.43         567595.43   
1  155966.02   245131.88  137811.38      NaN  538909.28         538909.28   

   Year  Notes         Agency Status  
0  2011    NaN  San Francisco    NaN  
1  2011    NaN  San Francisco    NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148049 non-null  object 
 4   OvertimePay       148654 non-null  object 
 5   OtherPay          148654 non-null  object 
 6   Benefits          112495 non-null  object 
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            38119 non-null   object 
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [4]:
df.shape

(148654, 13)

In [5]:
df.isnull()

Id  EmployeeName  JobTitle  BasePay  OvertimePay  OtherPay  \
0       False         False     False    False        False     False   
1       False         False     False    False        False     False   
2       False         False     False    False        False     False   
3       False         False     False    False        False     False   
4       False         False     False    False        False     False   
...       ...           ...       ...      ...          ...       ...   
148649  False         False     False    False        False     False   
148650  False         False     False    False        False     False   
148651  False         False     False    False        False     False   
148652  False         False     False    False        False     False   
148653  False         False     False    False        False     False   

        Benefits  TotalPay  TotalPayBenefits   Year  Notes  Agency  Status  
0           True     False             False  False   True   False    True  
1           True     False             False  False   True   False    True  
2           True     False             False  False   True   False    True  
3           True     False             False  False   True   False    True  
4           True     False             False  False   True   False    True  
...          ...       ...               ...    ...    ...     ...     ...  
148649     False     False             False  False   True   False   False  
148650     False     False             False  False   True   False    True  
148651     False     False             False  False   True   False    True  
148652     False     False             False  False   True   False    True  
148653     False     False             False  False   True   False   False  

[148654 rows x 13 columns]

In [6]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [7]:
df.dtypes

Id                    int64
EmployeeName         object
JobTitle             object
BasePay              object
OvertimePay          object
OtherPay             object
Benefits             object
TotalPay            float64
TotalPayBenefits    float64
Year                  int64
Notes               float64
Agency               object
Status               object
dtype: object

In [8]:
df["BasePay"].unique()

array([167411.18, 155966.02, 212739.13, ..., '6.04', '15.50',
       'Not Provided'], dtype=object)

In [9]:
df["BasePay"] = df["BasePay"].replace("Not Provided", np.nan)
df["BasePay"].unique()

array([167411.18, 155966.02, 212739.13, ..., '17.26', '6.04', '15.50'],
      dtype=object)

In [10]:
df["BasePay"] = df["BasePay"].astype(float)
df["BasePay"].dtypes
df["BasePay"].unique()

array([1.6741118e+05, 1.5596602e+05, 2.1273913e+05, ..., 1.7260000e+01,
       6.0400000e+00, 1.5500000e+01])

In [11]:
med = df["BasePay"].median()
med

65007.45

In [12]:
df["BasePay"] = df["BasePay"].replace(np.nan, med)
df["BasePay"].unique()

array([1.6741118e+05, 1.5596602e+05, 2.1273913e+05, ..., 1.7260000e+01,
       6.0400000e+00, 1.5500000e+01])

In [13]:
df["Agency"].unique()

array(['San Francisco'], dtype=object)

In [14]:
df["Agency"] = df["Agency"].astype("|S")
df["Agency"].dtypes

dtype('S13')

In [15]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [16]:
df["Benefits"] = df["Benefits"].fillna(df["Benefits"].median)
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits                 0
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [17]:
df.shape

(148654, 13)

In [18]:
df = df.drop(columns="Notes")
df.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                  0
OvertimePay              0
OtherPay                 0
Benefits                 0
TotalPay                 0
TotalPayBenefits         0
Year                     0
Agency                   0
Status              110535
dtype: int64

In [19]:
df["Status"].unique()

array([nan, 'PT', 'FT'], dtype=object)

In [20]:
df = df.dropna(subset=["Status"])
df.isna().sum()

Id                  0
EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
Agency              0
Status              0
dtype: int64

### Categorical to Quantitative variables 

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Status"] = le.fit_transform(df["Status"])
df.head(3)

Id          EmployeeName                  JobTitle    BasePay  \
110531  110532           David Shinn            Deputy Chief 3  129150.01   
110532  110533            Amy P Hart         Asst Med Examiner  318835.49   
110533  110534  William J Coaker Jr.  Chief Investment Officer  257340.00   

       OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
110531         0.0  342802.63  38780.04  471952.64         510732.68  2014   
110532    10712.95   60563.54  89540.23  390111.98         479652.21  2014   
110533         0.0    82313.7  96570.66  339653.70         436224.36  2014   

                  Agency  Status  
110531  b'San Francisco'       1  
110532  b'San Francisco'       0  
110533  b'San Francisco'       1

### Minmax Normalization

In [26]:
from sklearn.preprocessing import MinMaxScaler
arr = df["BasePay"].values.reshape(-1,1)
scaler = MinMaxScaler()
arr = scaler.fit_transform(arr)
df["BasePay"] = arr
df.head(5)

Id          EmployeeName                  JobTitle   BasePay  \
110531  110532           David Shinn            Deputy Chief 3  0.405068   
110532  110533            Amy P Hart         Asst Med Examiner  1.000000   
110533  110534  William J Coaker Jr.  Chief Investment Officer  0.807125   
110534  110535        Gregory P Suhr           Chief of Police  0.964291   
110535  110536  Joanne M Hayes-White    Chief, Fire Department  0.947410   

       OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
110531         0.0  342802.63  38780.04  471952.64         510732.68  2014   
110532    10712.95   60563.54  89540.23  390111.98         479652.21  2014   
110533         0.0    82313.7  96570.66  339653.70         436224.36  2014   
110534         0.0   19266.72  91302.46  326716.76         418019.22  2014   
110535         0.0   24165.44  91201.66  326233.44         417435.10  2014   

                  Agency  Status  
110531  b'San Francisco'       1  
110532  b'San Francisco'       0  
110533  b'San Francisco'       1  
110534  b'San Francisco'       0  
110535  b'San Francisco'       0

In [30]:
df["OvertimePay"] = df["OvertimePay"].astype(float)
max_op = df["OvertimePay"].max()
min_op = df["OvertimePay"].min()
df["OvertimePay"] = (df["OvertimePay"]-min_op)/(max_op-min_op)
df.head(5)

Id          EmployeeName                  JobTitle   BasePay  \
110531  110532           David Shinn            Deputy Chief 3  0.405068   
110532  110533            Amy P Hart         Asst Med Examiner  1.000000   
110533  110534  William J Coaker Jr.  Chief Investment Officer  0.807125   
110534  110535        Gregory P Suhr           Chief of Police  0.964291   
110535  110536  Joanne M Hayes-White    Chief, Fire Department  0.947410   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
110531     0.000000  342802.63  38780.04  471952.64         510732.68  2014   
110532     0.061729   60563.54  89540.23  390111.98         479652.21  2014   
110533     0.000000    82313.7  96570.66  339653.70         436224.36  2014   
110534     0.000000   19266.72  91302.46  326716.76         418019.22  2014   
110535     0.000000   24165.44  91201.66  326233.44         417435.10  2014   

                  Agency  Status  
110531  b'San Francisco'       1  
110532  b'San Francisco'       0  
110533  b'San Francisco'       1  
110534  b'San Francisco'       0  
110535  b'San Francisco'       0

### Z-score Normalization

In [33]:
df["OtherPay"] = df["OtherPay"].astype(float)
mean_op = df["OtherPay"].mean()
std_op = df["OtherPay"].std()
df["OtherPay"] = (df["OtherPay"] - mean_op) / std_op
df.head(5)

Id          EmployeeName                  JobTitle   BasePay  \
110531  110532           David Shinn            Deputy Chief 3  0.405068   
110532  110533            Amy P Hart         Asst Med Examiner  1.000000   
110533  110534  William J Coaker Jr.  Chief Investment Officer  0.807125   
110534  110535        Gregory P Suhr           Chief of Police  0.964291   
110535  110536  Joanne M Hayes-White    Chief, Fire Department  0.947410   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
110531     0.000000  43.683819  38780.04  471952.64         510732.68  2014   
110532     0.061729   7.346116  89540.23  390111.98         479652.21  2014   
110533     0.000000  10.146404  96570.66  339653.70         436224.36  2014   
110534     0.000000   2.029235  91302.46  326716.76         418019.22  2014   
110535     0.000000   2.659935  91201.66  326233.44         417435.10  2014   

                  Agency  Status  
110531  b'San Francisco'       1  
110532  b'San Francisco'       0  
110533  b'San Francisco'       1  
110534  b'San Francisco'       0  
110535  b'San Francisco'       0